spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customer-db
  cloud:
    discovery:
      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
server:
  port: 8081

