server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
# this part of configuration is for static routing
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/customers/**
#        - id: r2
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/products/** # we should not set space here !
    discovery:
      enabled: true
