spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:mem:product-db
  cloud:
    discovery:
      enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
server:
  port: 8082

