name: My first github actions workflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  job-1:
    # Job name is Greeting
    name: Job1-continious-integration
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: step-1-in-job-1-Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: step-2-in-job-1-Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
  job-2:
    name: Job-2-continious-integration
    runs-on: ubuntu-latest
    steps:
       - name: step-1-in-job-2-showing-how-to-use-env-variables
         run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
         env:
           FIRST_NAME: Mona
           middle_name: The
           Last_Name: Octocat