name: "Pull Request Labeler" # this name will be shown on the sidebar.
on:
  - pull_request
jobs:
  job-1: # this is not the name that will be shown.
  #If you need to set a name, we need to set a name attribute !
    name: should-add-label-after-a-pull-request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/config/label-config.yml'