# ref: https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions#running-on-a-different-operating-system
name: Node.js CI
on: [push]
defaults:
  run:
    working-directory: ./trying-multiple-config-angular/multiple-config
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
