# ref: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifacts
name: Node CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          cd trying-multiple-config-angular/multiple-config
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: trying-multiple-config-angular/multiple-config/dist/
