name: Redis Service Example

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image:  node:10.18-jessie

    services:
      redis:
        image: redis
        ports:
        - 6379:6379

    steps:
    - uses: actions/checkout@v2

    - run: npm ci # N.B: we need to run npm ci on redis folder to download redis dependency !!!
      working-directory: ./redis

    - run: node client.js
      working-directory: ./redis
      env:
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}

  vm-job:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2

    - run: npm ci
      working-directory: ./redis

    - run: node client.js
      working-directory: ./redis
      env:
        REDIS_HOST: localhost
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}